### ISSUE TITLE
Rebranding/Customizing

### ISSUE THREAD

**Issue by celskeggs** [sipb/uplink#7]
We aren't allowed to -- and don't want to -- have the name "Mattermost" all over everything; let's fix that.

 - [ ] also changing all of the help links to point to our own documents

**Comment by origamisaturn** [comment]
https://github.com/mattermost/docs/issues/1006

**Comment by gabrc52** [comment]
Some things:

- [ ] Choose a web client between Element and Cinny (or other?)
- [ ] Configure the theme and config to suit our needs
- [ ] Even more in the future, choose a mobile app, publish it and customize it

See:
Maybe some branding? https://github.com/aaronraimist/element-themes 

Just make it look more MIT and at least not green - because it looks very WhatsApp and also Apple uses green for SMS so it may be a bad idea because of that too

**Comment by gabrc52** [comment]
Also the email/web templates could be edited too: https://github.com/matrix-org/synapse/tree/master/synapse/res/templates 
Maybe make the templates use dark theme instead of light theme, or add some branding (SIPB logo and MIT logo —if permission)

If so, then on logging in, you could get a welcome DM from (instead of Clyde or Slackbot) Fuzzball? welcoming you to the app and for instance letting you know you can change your name, and how to do other things. (This can be done with the system alerts Synapse feature for instance)

**Comment by gabrc52** [comment]
https://chat.mozilla.org/ has a really nice screen and they also only use single-sign on like us

![image](https://user-images.githubusercontent.com/24363938/211241620-63ce56c6-a10f-44d0-b484-a65f5d05f014.png)

Their [config.json](https://chat.mozilla.org/config.json) can be a good starting point for how to setup this type of customization. Our current config immediately redirects you to sign-in which is okay but we currently can't add any welcome/other text/instructions

**Comment by gabrc52** [comment]
Also: we should customize the template for terms and conditions, and write some brief blurb saying

> Welcome to Matrix. This is how Matrix works.
> This service is provided "as-is" with no warranty. We will try our best to keep it running smoothly and you should feel free to reach out if you have any issues. The maintainers plan to rely on it, so it should be available 24/7 or really close. However, we also can't legally guarantee there won't be hiccups.
> Your messages are only end-to-end encrypted, and hence protected, if they say so. Public channels are not end-to-end encrypted because it wouldn't make sense to do so (also clients expect only private channels to be so).
> If a conversation isn't end to end encrypted, just like Messenger and Discord ones, we can't guarantee it's private. We promise not to look at it, and we promise to have a good security that guarantees we won't get hacked. But we can't guarantee it won't get hacked or that someone won't break into the SIPB office and steal your non-end-to-end encrypted messages.

Actually that sounds slightly terrifying, I'm just brainstorming...

But the point is that the template should be customized you and ask you 3 things

* Default question: do you agree to the terms? probably a checkbox
* Do you agree to be added to the rooms of the classes of the lists you're in? yes/no
* Do you agree to be added to the rooms of the mailing lists that have opted into the service? yes/no
* 
And add a hook to Synapse as a plugin after account creation, and instantly do the adding.  Try to implement it similarly to the auto join room feature, where you don't get asked if you want to join and instead get auto joined.

Alternatively, for the mailing list consent, if we can figure out a way for Synapse to hide invite rooms and only show them if someone has joined, then having people accept invitations also acts as consent to be in the groups. Basically, maybe what makes most sense is something like WhatsApp and Messenger and Signal do: if you get added to a gc and the person who adds you is not trusted tm, you get it as an invite request, but if the person is trusted tm, you're automatically in. But Matrix adding works as invite then join as opposed to just add.

**Comment by gabrc52** [comment]
To customize the Synapse pages, two templates to edit are definitely:

https://github.com/matrix-org/synapse/blob/master/synapse/res/templates/_base.html

https://github.com/matrix-org/synapse/blob/master/synapse/res/templates/sso_footer.html

**Comment by gabrc52** [comment]
Another thing we should customize is the "you have a new message" emails

![image](https://user-images.githubusercontent.com/24363938/213373127-35cce163-f7ab-428d-94eb-94e722c2a961.png)

If you click on "view" it takes you to https://app.element.io instead of our own hosted Element client

**Comment by gabrc52** [comment]
[ ] Add link to SIPB etc in footer
[ ] Customize emails
[ ] Add fuzzball next to [matrix]

**Comment by gabrc52** [comment]
![image](https://github.com/sipb/uplink/assets/24363938/814daa35-8d35-45ad-8fec-25973ecd853a)

**Comment by gabrc52** [comment]
![image](https://github.com/sipb/uplink/assets/24363938/aa9bac45-1df1-40cd-a179-aae250765d38)

We could also add the logo (or any other custom HTML) on the Element home once people are signed in

**Comment by gabrc52** [comment]
This is customized enough, I think we can close this issue.
